# Generated by Django 5.2.7 on 2025-10-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_visualization.region')),
            ],
            options={
                'db_table': 'sub_regions',
            },
            bases=('data_visualization.region',),
        ),
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_statistic', to='data_visualization.region')),
                ('sub_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_region_statistic', to='data_visualization.subregion')),
            ],
            options={
                'db_table': 'data_items',
            },
        ),
    ]
