version: '3.9'

services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/development/Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - docker/.env
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/.env
    ports:
      - "5432:5432"

volumes:
  static_volume: {}
  postgres_data: {}
